# Generated by Django 3.1 on 2021-07-08 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthdate', models.CharField(max_length=50)),
                ('about', models.CharField(blank=True, max_length=140, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile Details',
                'db_table': 'gamer_users',
                'ordering': ('-updated_at',),
            },
        ),
    ]
