# Generated by Django 3.1 on 2021-07-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameuser',
            table='gamer_users',
        ),
    ]
