# Generated by Django 3.1 on 2021-07-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameuser',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'Gamer User Details'},
        ),
        migrations.AlterModelTable(
            name='gameuser',
            table='gamer_users',
        ),
    ]
