# Generated by Django 3.1 on 2021-07-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0002_auto_20210709_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameuser',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'Gamer User Details'},
        ),
    ]
