# Generated by Django 3.1 on 2021-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0002_auto_20210709_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
