# Generated by Django 3.1 on 2021-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0003_auto_20210709_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='birthdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
